name: gh-deploy 


on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install --upgrade mkdocs-material       # https://squidfunk.github.io/mkdocs-material/upgrade/
      - run: pip3 install mkdocs-charts-plugin  # per fare grafici/charts (https://timvink.github.io/mkdocs-charts-plugin/)
      - run: pip install mkdocs-material-extensions>=1.0  
      - run: pip install mkdocs>=1.2.2
      - run: pip install markdown>=3.2  
      - run: pip install mkdocs-click
      - run: pip install Pygments>=2.4   
      - run: pip install pymdown-extensions>=9.0           
#     - run: pip install mkdocs-rss-plugin
      - run: pip install mkdocs-mermaid2-plugin   # fin qui il setting di https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/.github/workflows/gh-deploy.yml
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin    #  una prova del 3 dic 2021
#     - run: pip install mkdocs-jupyter           # attivato abilita "content tabs" e disabilita "code annotation"
#     - run: pip install requests_oauthlib  
#     - run: pip install click                              
#     - run: pip install click-plugins                      
#     - run: pip install click-config-file                  
#     - run: pip install pytest                             
#     - run: pip install mkdocs                             
#     - run: pip install mkdocstrings                          
#     - run: pip install pygments
#     - run: pip install pymdown-extensions                
#     - run: pip install mkdocs-autolinks-plugin            
#     - run: pip install mkdocs-exclude                    
#     - run: pip install mkdocs-exclude-search              
#     - run: pip install mkdocs-macros-plugin  
#     - run: pip install mkdocs-pdf-export-plugin
#     - run: pip install mkdocs-git-revision-date-localized-plugin   
#     - run: pip install mkdocs-windmill                             
#     - run: pip install mkdocs-img2fig-plugin                            
      - run: mkdocs gh-deploy --force
# setting by https://github.com/opendatasicilia/ods-mkdocs-material/blob/main/.github/workflows/gh-deploy.yml
